version: '3'

services:
  frontend:
    container_name: frontend
    develop:
      watch:
        - path: ./src/app
          action: sync
          target: /app/src/app
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    networks:
      - test-network
    ports:
      - 3000:3000
  api:
    container_name: api
    develop:
      watch:
        - path: ./backend/api
          action: sync
          target: /app/backend/api
    build:
      context: ./
      dockerfile: ./backend/api/Dockerfile
    networks:
      - test-network
    ports:
      - 8080:8080

networks:
  test-network:
    driver: bridge
